//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this sample source code is subject to the terms of the Microsoft
// license agreement under which you licensed this sample source code. If
// you did not accept the terms of the license agreement, you are not
// authorized to use this sample source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the LICENSE.RTF on your install media or the root of your tools installation.
// THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
/*++
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.

Module Name:  

<Provide Module Name>

Abstract:  

<Provide Abstract> 

Notes: 


--*/

#ifndef _UPDERRORS_H_
#define _UPDERRORS_H_

#include <winerror.h>

#define E_INVALID_DSM                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE+ 1))
#define E_MISSING_DSM                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 2))
#define E_DSMCAB_FILE                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 3))
#define E_CABDSM_FILE                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 4))
#define E_NOT_CAB                           MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 5))
#define E_UNSUPPORTED_COMPRESSION         MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 6))
#define E_DECOMPRESS_FAILURE               MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 7))
#define E_INVALID_SIGNATURE                MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 8))
#define E_OLD_INTERFACE_VERSION            MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 9))
#define E_GENERAL_GRAPH_FAILURE           MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 10))
#define E_DUPLICATE_PACKAGE               MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 11))
#define E_MISSING_DEPENDENCY              MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 12))
#define E_INCORRECT_VERSION_DEP           MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 13))
#define E_INSUFFICIENT_SPACE               MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 14))
#define E_INVALID_CPU                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 15))
// #define E_PACKAGE_NOT_NEEDED               MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 15))
#define E_NO_TEMP_DIR                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 16))
#define E_NO_PACKAGES                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 17))
#define E_LIST_CONSTRUCTION_ERROR        MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 18))
#define E_CANONICAL_IS_EXISTING         MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 19))
#define E_GRAPH_WALK_FAILURE			MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 20))
#define E_NO_VALID_PATHS                         MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 21))
#define E_NULL_GRAPH                                MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 22))
#define E_MISSING_CERT_INFO                  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 23)) //keeping this error code for back compat
#define E_MISSING_CERTIFICATE                  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 23))
#define E_BAD_CERT_DATA                         MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 24))
#define E_INVALID_PATH                              MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 25))
#define E_RESET_GRAPHWALK                       MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 26))
#define E_INVALID_PARTITION                     MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 27))
#define E_NAME_MISMATCH                         MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 28))
#define E_FATAL_FILE_COLLISION              MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 29)) 
#define E_GENERAL_FILE_COLLISION          MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 30))
#define E_INCORRECT_DIFF_PACKAGE          MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 31))
#define E_RESERVED_FILE_NAME_COLLISION  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 32))
#define E_NO_RESERVED_SECTION_PRESENT  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 33))
#define E_UNKNOWN_RESERVED_SECTION   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 34)) 
#define E_INCORRECT_DELETE_PKG   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 35)) 
#define E_DUPLICATE_DELETE_PKG   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 36)) 
#define E_INVALID_DELETE_PKG   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 37))
#define E_INVALID_DELETE_PKG_VERSION   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 38))
#define E_INVALID_DELETE_PATH   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 39))
#define E_INVALID_DELETE_AUTHORITY   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 40))
#define E_DEPENDENCY_ON_DELETED_PKG   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 41))
#define E_NONSINGULAR_ULDR_UPDATE   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 42))
#define E_CANNOT_ADD_NEW_ULDR_PKG   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 43))
#define E_ANOTHER_UPDATE_ALREADY_IN_PROGRESS  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 44)) 
#define E_OUT_OF_NK_SPACE  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 45)) 
#define E_OUT_OF_ULDR_SPACE  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 46)) 
#define E_CANT_WRITE_RESERVE_REGION  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 47)) 
#define E_CANT_READ_RESERVE_REGION  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 48)) 
#define E_OUT_OF_IMGFS_SPACE  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 49)) 
#define E_OUT_OF_RAM  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 50)) 
#define E_OUT_OF_TFAT_SPACE  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 51)) 
#define E_OUT_OF_VM  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 52)) 
#define E_MISSING_DEFAULT_CERT_STORE  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 53))  
#define E_NO_CERT_IN_BASE_PKG  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 54))
#define E_CIRCULAR_SHADOWING  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 55)) 
#define E_INVALID_VM_RANGE  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WINDOWS_CE, (UPDERROR_BASE + 56)) 

#define S_EXISTING_NODE                    MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_WINDOWS_CE, (UPDSUCCESS_BASE + 1))
#define S_NO_PATHS                          MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_WINDOWS_CE, (UPDSUCCESS_BASE + 2))
#define S_PACKAGE_NOT_NEEDED               MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_WINDOWS_CE, (UPDSUCCESS_BASE + 3))
#define S_NO_RESERVE_SECTION_PRESENT               MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_WINDOWS_CE, (UPDSUCCESS_BASE + 4))
#define S_CANT_USE_THIS_PKG_WITH_DELETE               MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_WINDOWS_CE, (UPDSUCCESS_BASE + 5))


#endif
