//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this sample source code is subject to the terms of the Microsoft
// license agreement under which you licensed this sample source code. If
// you did not accept the terms of the license agreement, you are not
// authorized to use this sample source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the LICENSE.RTF on your install media or the root of your tools installation.
// THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
/*++

Module Name:

    permdlg.idl

Abstract:

    Dialog popup for displaying Permission data

--*/

import "urlmon.idl";

cpp_quote("EXTERN_C const CLSID CLSID_JavaRuntimeConfiguration;")

[
    object,
    uuid(85347F8A-C8B7-11d0-8823-00C04FB67C84),
    pointer_default(unique) 
] 
interface IJavaZonePermissionEditor : IUnknown
{   
    typedef enum _JAVADISPLAYMODES
    {
        JAVADISPLAY_DEFAULT=0,   // Default display for clients
        JAVADISPLAY_FULL   =1,   // Full display for administrators
        JAVAEDIT           =2,   // Edit 
    } JAVADISPLAYMODES;

    HRESULT ShowUI (
        [in]    HWND        phwnd,         // Parent window
        [in]    DWORD       dwFlags,       // reserved
        [in]    DWORD       dwMode,        // See JAVADISPLAYFLAGS
        [in]    URLZONEREG  urlZoneReg,    // Location HKCU, and HKLM
        [in]    DWORD       dwZone,        // Zone index
        [in]    DWORD       dwPerms,       // Permissions to edit (0 for zone default)
        [in]    IUnknown    *pManager);    // Provide IInternetZoneManager
};

[
	uuid(004CE610-CCD1-11d0-A9BA-00A0C908DB5E)
]
coclass JavaRuntimeConfiguration
{
	interface IJavaZonePermissionEditor;
}

